apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com      # Add IAM policy about EBS_CNI_DRIVER into role
# volumeBindingMode: WaitForFirstConsumer 
parameters:
  type: gp3
reclaimPolicy: Retain
mountOptions:
  - debug
  